### PR TITLE
Set ID on anchors

### PR DESCRIPTION
**Pull request by gavboulton**
When reloading a page with a previous tab selected, the same tab is not setup correctly. The module currently expects the anchors to have an ID with a prefix of `label_`. Set this ID explicitly on each anchor so that it does not need to be included in the static markup.

Git ignore node_modules directory.

### CODE REVIEW

**Comment by gavboulton** [comment]
Most of the difference in the distributed files are due to whitespace.

**Comment by nico3333fr** [comment]
Thanks a lot, good idea :)

**Comment by nico3333fr** [comment]
I've updated the demos and doc, following your update. Thanks again for your patience 👍

**Comment by gavboulton** [comment]
Cool, thanks.

**Pull request merged**
